# version: '3.8'

services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/password  
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      # - neo4j_config:/config
      # - neo4j_plugin:/plugin

  python-app:
    build:
      context: .  
    container_name: python-app
    depends_on:
      - neo4j
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - "8000:8000"  

volumes:
  neo4j_data:
  neo4j_logs: