GetKeywordPrompt = "Please analyze the article called \"{article}\" and identify top five key concepts as keywords, don't include extraneous information."
GetCooperateSuggestion = "Suggest how to cooperate between {professor1} and {professor2}, their common interest is {common_interest}, {professor1} {professor1_interest}, {professor2} {professor2_interest}"
GetAnalysisProfessor = "Give me a brief analysis of the research interests and strength of {professor}"
GoogleScholarURL = "https://scholar.google.com/citations?user={user}&cstart=0&pagesize=30"
mysecret = ""